# Generated by Django 4.1.7 on 2023-07-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts',
            field=models.ManyToManyField(related_name='author_posts', to='board.post'),
        ),
    ]
